set -g mouse on
setw -g mode-keys vi

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
bind-key o capture-pane -J \; save-buffer /tmp/tmux-buffer \; new-window "grep -Eo 'https?://[^ ]+' /tmp/tmux-buffer | fzf | xargs open"
